### ISSUE TITLE
themes.framework constant required

### ISSUE THREAD

**Issue by tdeuling** [smadsen/theme_foundation#2]
Hi,
please be sure that you have a constant that defines the used framework, like:

themes.framework = Foundation

Here's the equivalent theme_bootstrap file:
https://github.com/typo3-themes/theme_bootstrap/blob/master/Configuration/TypoScript/Library/themes.constantsts

Thanks

**Comment by rafch** [comment]
Hi,
Ok, done!

Have a nice day.
Raf
