### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by DanielRuf** [smadsen/theme_foundation#5]
It seems this project is not actively maintained or developed anymore. Is this the case?

**Comment by kaystrobach** [comment]
we are currently focussing on bootstrap 3 and 4.
If you have any patches bugs, please let us know, if it is a small thing we happily integrate that.

If you want to rely on that project in a commercial one, you can buy support via sponsoring or via an sla, feel free to contact me for more details.

**Comment by DanielRuf** [comment]
I've expected a theme which integrates Foundation Sites 6(.4.3) and which is a good implementation of it and is also actively maintained.

If this is not the case and you switched to Bootstrap I might fork it and incubate it / provide it as contributed community solution for Foundation Sites 6.

**Comment by kaystrobach** [comment]
if you want to contribute, you're highly welcome.

Feel free to provide PRs, I think the team will happily review it :)

**Comment by daybugging** [comment]
As always, people "expect" quality for free - where are all the promised PRs, @DanielRuf?

**Comment by DanielRuf** [comment]
@daybugging sorry but I'm busy with work and other projects at the moment + the work as Yetinaut / Foundation core dev is also more than nothing ;-)

**Comment by DanielRuf** [comment]
Basically I just asked if the project is still maintained / support to know if we can collaborate or if we would incubate it with other Foundation projects this year.

**Comment by DanielRuf** [comment]
PS: I guess you can clearly see on my profile that I contribute much to OSS in my free time ;-)

**Comment by DanielRuf** [comment]
> If this is not the case and you switched to Bootstrap I might fork it and incubate it / provide it as contributed community solution for Foundation Sites 6.

I'm not interested in working with Bootstrap btw ;-)

**Comment by kaystrobach** [comment]
Heyla, thank you for asking, i would happily review patches and lateron would happily welcome you in the team.

Thanks a lot
Kay
